import React from 'react'
import ReactDOM from 'react-dom'
//import { Padre } from './components/07-tarea-memo/Padre'
import { TodoApp } from './components/useReducer/TodoApp'
//import CallbackHook from './components/memos/CallbackHook'
//import MemoHook from './components/memos/MemoHook'
//import Memorize from './components/memos/Memorize'
//import UseLayoutEffect from './components/useLayoutEffect/UseLayoutEffect'
//import MultipleCustomHooks from './components/examples/MultipleCustomHooks'
//import FocusScreen from './components/useRef/FocusScreen'
//import RealExampleUseRef from './components/useRef/RealExampleUseRef'
//import FormWithCustomHooks from './components/useEffect/FormWithCustomHooks'
//import SimpleForm from './components/useEffect/SimpleForm'
//import CounterApp from './components/useState/CounterApp'
//import CounterWithCustomHook from './components/useState/CounterWithCustomHook'
//import HooksApp from './HooksApp'

ReactDOM.render(<TodoApp />, document.getElementById('root'))
